# This is your sidebar TOC. The sidebar code loops through sections here and provides the appropriate formatting.

entries:
- title: Sidebar
  product: Foundations
  version: 1.0
  levels: one
  folders:

  - title:
    output: pdf
    type: frontmatter
    folderitems:
    - title:
      url: /titlepage
      output: pdf
      type: frontmatter
    - title:
      url: /tocpage
      output: pdf
      type: frontmatter

  - title: Requirements
    output: web, pdf
    folderitems:
    - title: Foundations
      url: /foundations_reqs.html
      output: web, pdf
